language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

before_script:
  - composer self-update

matrix:
  allow_failures:
    - php: 7
    - php: hhvm
	

install: travis_retry composer install --no-interaction --prefer-source
	
script:
  - ./vendor/bin/phpcs lib --standard=PSR2
  - ./vendor/bin/phpunit
